spring:
  mvc:
    servlet:
      load-on-startup: 1
    static-path-pattern:
      /**
  datasource:
#   数据源基本配置
    username: root
    password: YJzj0610&
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/offershow
  web:
    resources:
      static-locations:
        classpath:/static/
    
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
server:
  port: 80

